name: using matrix

on: push

jobs: 
  using_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: log node version
        run: log -v 
      - uses: actions/setup-node@v1
        with: 
          node_version: 6
      - name: log node version
        run: log -v



