name: simple action

on:
  repository_dispatch:
    types: [build]
  #push:
  pull_request:
    types: [ reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo "${{ github.event.client_payload.env }}"
      - name: run shell commands
        run: |
          ls -a
          pwd
          echo "$GITHUB_SHA"
          echo "$GITHUB_REPOSITORY"
          echo "$GITHUB_WORKSPACE"
          echo "${{ github.token }}"
      - name: checkout action
        uses: actions/checkout@v1
      - name: after the checkout action
        run: |
          ls -a
          pwd 
      - name: simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: sasank

      - name: detect log time
        run: echo "${{ steps.greet.outputs.time }}"