name: shell commands

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: run a shell command
        run: echo "hello world"

      - name: run multiline script
        run: |
          node -v
          npm -v
      
      - name: run python command
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-command:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: get directiory
        run: Get-Location

      - name: get directiory
        run: pwd
        shell: bash
